### ISSUE TITLE
Outdated kubernetes version

### ISSUE THREAD

**Issue by abdennour** [prabhatsharma/kubernetes-the-hard-way-aws#1]
As per Exam tips document of CNCF, the current kubernetes version is 1.12. However, this repository is about kubernetes v1.11 currently.

**Comment by ryanbrainard** [comment]
This issue can probably be closed by https://github.com/prabhatsharma/kubernetes-the-hard-way-aws/pull/4.

**Comment by prabhatsharma** [comment]
upgraded to 1.15
